# Use Node.js LTS
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy source code
COPY . .

# Expose port
EXPOSE 5000

# Set environment variables (Defaults)
ENV NODE_ENV=production
ENV PORT=5000

# Start the server
CMD ["node", "server.js"]
